image:
  repository: wavefronthq/wavefront-hpa-adapter
  tag: 0.9.10
  pullPolicy: IfNotPresent

## Wavefront URL (cluster) and API Token
## Required
wavefront:
  url: https://YOUR_CLUSTER.wavefront.com

# Required one of the following:
  # OPTIONAL, Wavefront API token with permissions to query for points. If token is not provided, the adapter will look for a secret.
  token: YOUR_API_TOKEN

  # OPTIONAL, Allow to use a secret to pull the credentials.
  secret:
    # Name of the secret containing the Wavefront API token
    name: ""

    # Key in the secret containing the Wavefront API token
    key: "api-token"

adapter:
  # Metrics under this prefix are exposed via the custom metrics API
  metricPrefix: kubernetes

  # Interval at which to fetch the list of custom metric names from Wavefront
  metricRelistInterval: 10m

  # API client timeout
  apiClientTimeout: 10s

  # one of info, debug, warn or trace
  logLevel: info

  # List wavefront queries to transform into external metrics
  # See https://github.com/wavefrontHQ/wavefront-kubernetes-adapter/blob/master/docs/introduction.md#static-configuration-file
  # rules:
  #   - query: 'ts(azure.compute.vm.percentage.cpu)'
  #     name: azure.vm.cpu
  #   - query: 'ts(aws.sqs.approximatenumberofmessagesvisible)'
  #     name: aws.sqs.messagesvisible

resources: {}
  # limits:
  #   cpu: 50m
  #   memory: 100Mi
  # requests:
  #   cpu: 5m
  #   memory: 20Mi

priorityClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}
